method: eagle

# path to the VCF file of all the genotypes you want phased.
# This must be indexed (i.e. with bcftools).
vcf_input: ".test/data/small.vcf.gz"

# path to the Eagle executable. (Only runs on Linux)
eagle_path: bin/eagle-Linux

# path to the two columns TSV file (with no column names). The first
# column is the chromosome name as it appears in the input VCF/BCF
# file and the second is the integer equivalent
eagle_chrom_file: .test/config-test-eagle/mykiss_chroms.tsv


# A map file that specifies 1 centiMorgan per megabase on all chromosomes.
# This is used if a good recombination map is not available for your
# species. Used by eagle
eagle_map_input: "inputs/genetic_map_1cMperMb.txt"

