

include: "rules/common.smk"



# rule all for the eagle method
if config["method"] == "eagle":
	rule all:
		input: expand("results/{method}/phased_bcf/chr-{chrom}.bcf.csi", method = config["method"], chrom = chrom_list)


if config["method"] == "beagle":
	rule all:
		input: 
			"results/beagle/all-beagle-phased.vcf.gz"



if config["method"] == "eagle":
	include: "rules/eagle.smk"


if config["method"] == "beagle":
	include: "rules/beagle.smk"