cluster:
  mkdir -p results/slurm_logs/{rule} &&
  sbatch
    --partition=standard
    --cpus-per-task={threads}
    --time={resources.time}
    --job-name=smk-{rule}-{wildcards}
    --output=results/slurm_logs/{rule}/{rule}-%j-{wildcards}.out
    --error=results/slurm_logs/{rule}/{rule}-%j-{wildcards}.err
    --parsable
cluster-status: status-sacct-robust.sh
cluster-cancel: scancel
cluster-cancel-nargs: 400
default-resources:
  - time="08:00:00"
restart-times: 0
max-jobs-per-second: 10
max-status-checks-per-second: 25
local-cores: 1
latency-wait: 60
cores: 2400
jobs: 950
keep-going: True
rerun-incomplete: True
printshellcmds: True
use-conda: True
rerun-trigger: mtime


set-threads:
  beagle_impute: 10
  beagle_phase: 10
